baseURL = "http://example.org/"
languageCode = "en-us"
title = "thangtmc73"
theme = "archie"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[params]

  colortheme = "white" # dark, light, white, or classic